name: gh-pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish ./web/z80wasm.csproj -c Release -o release --nologo
      
    # changes the base-tag in index.html from '/' to 'z80.wasm' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/z80.wasm\/" \/>/g' release/wwwroot/index.html
  
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
  
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: gh-pages-from-actions # The branch the action should deploy to.
        FOLDER: release/wwwroot # The folder the action should deploy.
        SINGLE_COMMIT: true
